#!/bin/bash
#$ -N info_rect
#$ -l mem=2G
#$ -l h_rt=72:00:00
#$ -cwd
#$ -pe default 4
#$ -o /net/store/scratch/odd/valid_until_31_jan_2018/lbechberger/sge-logs/
#$ -e /net/store/scratch/odd/valid_until_31_jan_2018/lbechberger/sge-logs/

export PATH="$HOME/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

source activate infogan

PYTHONPATH='.' python launchers/run_rectangle_exp.py $1

source deactivate infogan

rm /tmp/* -R -f 2> /dev/null
