#!/bin/bash
#$ -N betavae
#$ -l mem=5G
#$ -l h_rt=1:30:00
#$ -cwd
#$ -pe default 4
#$ -l cuda=1
#$ -l cuda_cores=384
#$ -l nv_mem_free=1200M
#$ -o /dev/null
#$ -e /dev/null

export PATH="/net/projects/scratch/winter/valid_until_31_July_2019/lbechberger/miniconda/bin:$PATH"
rm /tmp/* -R -f 2> /dev/null

date
source activate tensorflow-CS

t=$(( $SGE_TASK_LAST - $SGE_TASK_ID + 2))

python -u run_betavae.py 

source deactivate tensorflow-CS

date

rm /tmp/* -R -f 2> /dev/null
